import './globals.css'

import { Inter, Space_Mono } from 'next/font/google'

import LayoutContainer from './LayoutContainer'

const inter = Inter({ subsets: ['latin'] })
const spaceMono = Space_Mono({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className="light">
			<head>
				<meta charSet="UTF-8" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<title>{metadata.title}</title>
				<meta name="description" content={metadata.description} />
			</head>
			<body className={`${inter.className} ${spaceMono.className}`}>
				<LayoutContainer>{children}</LayoutContainer>
			</body>
		</html>
	)
}
